### ISSUE TITLE
Story - Schema validator

### ISSUE THREAD

**Issue by fedefernandez** [frees-io/freestyle-cassandra#17]
As part of this story we should:
- [x] Spike #47 
- [x] Define the keyspace and table models - Issue #24 
- [x] Add a mechanism (through implicits?) for retrieving schema information, providing different strategies (local schema sql, remote connection to the db, ...) - Issue #27
- [x] Add a schema parser for keyspaces - PR #15 
- [x] ~Add a scheme parser for tables~ - Not needed (#49)
- [x] Implement a local schema sql provider - Issue #49
- [x] Implement a remote scheme provider - Issue #51
