### ISSUE TITLE
Story - Object mapper

### ISSUE THREAD

**Issue by fedefernandez** [frees-io/freestyle-cassandra#18]
- [x] Spike #46 
- [x] FieldMapper (from case class to `List[(String, ByteBuffer)]`) - #38 
- [ ] Insert statement from a case class - #124
- [ ] Populate a prepared statement with a case class instance - #125 
- [ ] Method for inserting case class instances - #126 
- [ ] Select statements from case classes - #127  
- [ ] Fetch case classes instances - #128  
- [ ] Unify all methods under the same `class`/`trait`
